{% set name = "pennylane" %}
{% set version = "0.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  - git_url: https://github.com/PennyLaneAI/pennylane-lightning.git
    git_rev: 69900a635df12d53269c60e026b35a7238e08062
    folder: pennylane-lightning
    # url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
    # sha256: f5849c2affb5fb57aca20feb40ca829d171b07db2304fde0a37c2332c5b09e18
    # patches:
    #   - 0001-Non-ninja.patch
    #   # Ninja is not recognised by pip check.
  - url: https://github.com/PennyLaneAI/pennylane/archive/v{{ version }}.tar.gz
    sha256: 7736a17dc972d918e3a737ce4360d16ac84b9f9f6fca440f167de579c926c114
    folder: pennylane

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Needed for Windows
    - cmake
    - ninja
    - make
  host:
    - python
  run:
    - python
    - pennylane-core
    - pennylane-lightning-core
    
test:
  imports:
    - pennylane
  commands:
    - pip check
    - cd "${SRC_DIR}/../work/pennylane" && {{ PYTHON }} -m pytest tests/test_qubit_device.py tests/devices/test_lightning_qubit.py
    - cd "${SRC_DIR}/../work/pennylane" && {{ PYTHON }} -m pytest tests --dist worksteal -n auto --tb=native --no-flaky-report --cov=pennylane --cov-report term-missing --cov-report=html:coverage_html_report
  requires:
    - setuptools <=64.0.2 # version requirement from cvxpy
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-xdist
    - flaky

outputs:

  - name: pennylane-core
    version: {{ version }}
    build:
      run_exports:
        - {{ pin_subpackage('pennylane-core', max_pin='x.x') }}
      entry_points:
        - pl-device-test=pennylane.devices.tests:cli
      script: cd "${SRC_DIR}/pennylane" && {{ PYTHON }} -m pip install . -vv
      number: 0
    requirements:
      host:
        - pip
        - python
      run:
        - appdirs
        - autograd
        - autoray ==0.3.1
        - cachetools
        - cvxopt
        - cvxpy
        - networkx
        - numpy <1.24
        - opt_einsum
        - python
        - requests
        - retworkx
        - scipy
        - semantic_version >=2.10
        - toml

  - name: pennylane-lightning-core
    version: {{ version }}
    build:
      run_exports:
        - {{ pin_subpackage('pennylane-lightning-core', max_pin='x.x') }}
      number: 0
      # skip: true  # [win and vc<14]
      skip: true  # [win]
      script: cd "${SRC_DIR}/pennylane-lightning" && {{ PYTHON }} -m pip install . -vv
    requirements:
      build:
        - {{ compiler('c') }}
        - {{ compiler('cxx') }}
        # Needed for Windows
        - cmake
        - ninja
        - make
      host:
        - libblas
        - liblapacke
        - libgomp      # [linux]
        - llvm-openmp  # [osx]
        - pip
        - pybind11
        - python
        - setuptools <=64.0.2 # version requirement from cvxpy
      run:
        - ninja
        - numpy
        - python

about:
  home: https://github.com/PennyLaneAI/pennylane
  summary: PennyLane is a Python quantum machine learning library by Xanadu Inc.
  license: Apache-2.0 AND MIT
  # MIT is pennylane/grouping/graph_colouring.py
  license_file: pennylane/LICENSE
  doc_url: https://pennylane.readthedocs.io/en/stable/

extra:
  recipe-maintainers:
    - BastianZim
    - vincentmr
