{% set name = "pennylane-lightning" %}
{% set version = "0.25.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 43aec97d43ad41d4430c3876feb3271050c0b0ae359a3af7f8806b1f76f3f404
  patches:
    - 0001-Non-ninja.patch
    # Ninja is not recognised by pip check.

build:
  number: 0
  # skip: true  # [win and vc<14]
  skip: true  # [win]
  # Kokkos is currently not available
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - setuptools
    # Needed for Windows
    - cmake
    - ninja
    - make
  host:
    - kokkos
    - libblas
    - liblapacke
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
  run:
    - ninja
    - numpy
    - pennylane >=0.19
    - python

test:
  imports:
    - pennylane_lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PennyLaneAI/pennylane-lightning
  summary: PennyLane-Lightning plugin
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane-lightning.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
