{% set name = "pennylane-lightning" %}
{% set version = "0.44.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 87074a11c4482c27cd1ae8212536873577609c0cced4cba928674fd6c2dff3ad
  patches:
    - 0001-Non-ninja.patch
    # Ninja is not recognised by pip check.

build:
  number: 0
  # skip: true  # [win and vc<14]
  skip: true  # [win]
  # Kokkos is currently not available
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
    - setuptools
    # Needed for Windows
    - cmake
    - ninja
    - make
  host:
    - kokkos
    - libblas
    - liblapacke
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
  run:
    - scipy-openblas32 >=0.3.26
    - ninja
    - numpy
    - pennylane >=0.42
    - python

test:
  imports:
    - pennylane_lightning
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/PennyLaneAI/pennylane-lightning
  summary: PennyLane-Lightning plugin
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane-lightning.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - vincentmr
    - BastianZim
