{% set name = "pennylane-lightning" %}
{% set version = "0.28.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  git_url: https://github.com/PennyLaneAI/pennylane-lightning.git
  git_rev: 69900a635df12d53269c60e026b35a7238e08062
  # url: https://github.com/PennyLaneAI/pennylane-lightning/archive/refs/tags/v{{ version }}.tar.gz
  # sha256: f5849c2affb5fb57aca20feb40ca829d171b07db2304fde0a37c2332c5b09e18
  # patches:
  #   - 0001-Non-ninja.patch
  #   # Ninja is not recognised by pip check.

build:
  number: 0
  # skip: true  # [win and vc<14]
  skip: true  # [win]
  # Kokkos is currently not available
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    # Needed for Windows
    - cmake
    - ninja
    - make
  host:
    - libblas
    - liblapacke
    - libgomp      # [linux]
    - llvm-openmp  # [osx]
    - pip
    - pybind11
    - python
    - setuptools
  run:
    - ninja
    - numpy
    - pennylane >=0.23
    - python

test:
  imports:
    - pennylane_lightning
  # commands:
  #   - pip check
  requires:
    - pip

about:
  home: https://github.com/PennyLaneAI/pennylane-lightning
  summary: PennyLane-Lightning plugin
  license: Apache-2.0
  license_file: LICENSE
  doc_url: https://pennylane-lightning.readthedocs.io/en/latest/

extra:
  recipe-maintainers:
    - BastianZim
